[book]
authors = ["rest"]
language = "en"
multilingual = false
src = "src"
title = "rest_libcint Document"

[preprocessor.katex]
after = ["links"]

[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]
